
project:
  type: website
  render:
    - "**/*.qmd"
    - "**/*.ipynb"

website:
  title: "POO et DOC"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: TP
        menu: 
          - href: doc/tp/tp1.qmd
            text: "TP n°1"
          - href: doc/tp/tp2.qmd
            text: "TP n°2"
    right:
      - icon: github
        href: https://github.com/ludo2ne/ENSAI-1A-POO-TP
        target: "_blank"        
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"}  
      [Code source](https://github.com/ludo2ne/ENSAI-1A-POO-TP){.external target="_blank"}
  repo-url: https://github.com/ludo2ne/ENSAI-1A-POO-TP
  repo-branch: main
  reader-mode: true      

format:
  html:
    theme: 
      dark: solar
      light: cosmo
    css: styles.css



